#! vim: ft=yaml ts=2:
---

- name: include OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: assertions
  assert:
    that:
      - ansible_os_family == 'RedHat'
      - ansible_distribution_major_version in ["7"]

- name: rng-tools are present
  package:
    name: rng-tools
    state: present 

- name: rngd is running
  service:
    name: "{{ rng.rng_tools_service }}"
    state: started
    enabled: true
